/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Booking,
  BookingInput,
  BookingUpdate,
  BookingsSummary,
  GalleryPhoto,
  GalleryPhotoInput,
  HealthStatus,
  Service,
  ServiceInput,
  ServiceUpdate
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListServicesUrl = () => {




  return `/api/services`
}

/**
 * @summary List all wedding services
 */
export const listServices = async ( options?: RequestInit): Promise<Service[]> => {

  return customFetch<Service[]>(getListServicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListServicesQueryKey = () => {
    return [
    `/api/services`
    ] as const;
    }


export const getListServicesQueryOptions = <TData = Awaited<ReturnType<typeof listServices>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListServicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listServices>>> = ({ signal }) => listServices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData> & { queryKey: QueryKey }
}

export type ListServicesQueryResult = NonNullable<Awaited<ReturnType<typeof listServices>>>
export type ListServicesQueryError = ErrorType<unknown>


/**
 * @summary List all wedding services
 */

export function useListServices<TData = Awaited<ReturnType<typeof listServices>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListServicesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateServiceUrl = () => {




  return `/api/services`
}

/**
 * @summary Create a new service
 */
export const createService = async (serviceInput: ServiceInput, options?: RequestInit): Promise<Service> => {

  return customFetch<Service>(getCreateServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serviceInput,)
  }
);}




export const getCreateServiceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createService>>, TError,{data: BodyType<ServiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createService>>, TError,{data: BodyType<ServiceInput>}, TContext> => {

const mutationKey = ['createService'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createService>>, {data: BodyType<ServiceInput>}> = (props) => {
          const {data} = props ?? {};

          return  createService(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateServiceMutationResult = NonNullable<Awaited<ReturnType<typeof createService>>>
    export type CreateServiceMutationBody = BodyType<ServiceInput>
    export type CreateServiceMutationError = ErrorType<unknown>

    /**
 * @summary Create a new service
 */
export const useCreateService = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createService>>, TError,{data: BodyType<ServiceInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createService>>,
        TError,
        {data: BodyType<ServiceInput>},
        TContext
      > => {
      return useMutation(getCreateServiceMutationOptions(options));
    }

export const getListFeaturedServicesUrl = () => {




  return `/api/services/featured`
}

/**
 * @summary List featured services for homepage
 */
export const listFeaturedServices = async ( options?: RequestInit): Promise<Service[]> => {

  return customFetch<Service[]>(getListFeaturedServicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFeaturedServicesQueryKey = () => {
    return [
    `/api/services/featured`
    ] as const;
    }


export const getListFeaturedServicesQueryOptions = <TData = Awaited<ReturnType<typeof listFeaturedServices>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFeaturedServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFeaturedServicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFeaturedServices>>> = ({ signal }) => listFeaturedServices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFeaturedServices>>, TError, TData> & { queryKey: QueryKey }
}

export type ListFeaturedServicesQueryResult = NonNullable<Awaited<ReturnType<typeof listFeaturedServices>>>
export type ListFeaturedServicesQueryError = ErrorType<unknown>


/**
 * @summary List featured services for homepage
 */

export function useListFeaturedServices<TData = Awaited<ReturnType<typeof listFeaturedServices>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFeaturedServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListFeaturedServicesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetServiceUrl = (id: number,) => {




  return `/api/services/${id}`
}

/**
 * @summary Get service by ID
 */
export const getService = async (id: number, options?: RequestInit): Promise<Service> => {

  return customFetch<Service>(getGetServiceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetServiceQueryKey = (id: number,) => {
    return [
    `/api/services/${id}`
    ] as const;
    }


export const getGetServiceQueryOptions = <TData = Awaited<ReturnType<typeof getService>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getService>>> = ({ signal }) => getService(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceQueryResult = NonNullable<Awaited<ReturnType<typeof getService>>>
export type GetServiceQueryError = ErrorType<void>


/**
 * @summary Get service by ID
 */

export function useGetService<TData = Awaited<ReturnType<typeof getService>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateServiceUrl = (id: number,) => {




  return `/api/services/${id}`
}

/**
 * @summary Update a service
 */
export const updateService = async (id: number,
    serviceUpdate: ServiceUpdate, options?: RequestInit): Promise<Service> => {

  return customFetch<Service>(getUpdateServiceUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      serviceUpdate,)
  }
);}




export const getUpdateServiceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateService>>, TError,{id: number;data: BodyType<ServiceUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateService>>, TError,{id: number;data: BodyType<ServiceUpdate>}, TContext> => {

const mutationKey = ['updateService'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateService>>, {id: number;data: BodyType<ServiceUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateService(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateServiceMutationResult = NonNullable<Awaited<ReturnType<typeof updateService>>>
    export type UpdateServiceMutationBody = BodyType<ServiceUpdate>
    export type UpdateServiceMutationError = ErrorType<unknown>

    /**
 * @summary Update a service
 */
export const useUpdateService = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateService>>, TError,{id: number;data: BodyType<ServiceUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateService>>,
        TError,
        {id: number;data: BodyType<ServiceUpdate>},
        TContext
      > => {
      return useMutation(getUpdateServiceMutationOptions(options));
    }

export const getDeleteServiceUrl = (id: number,) => {




  return `/api/services/${id}`
}

/**
 * @summary Delete a service
 */
export const deleteService = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteServiceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteServiceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteService>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteService>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteService'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteService>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteService(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteService>>>

    export type DeleteServiceMutationError = ErrorType<unknown>

    /**
 * @summary Delete a service
 */
export const useDeleteService = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteService>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteService>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteServiceMutationOptions(options));
    }

export const getListBookingsUrl = () => {




  return `/api/bookings`
}

/**
 * @summary List all bookings
 */
export const listBookings = async ( options?: RequestInit): Promise<Booking[]> => {

  return customFetch<Booking[]>(getListBookingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBookingsQueryKey = () => {
    return [
    `/api/bookings`
    ] as const;
    }


export const getListBookingsQueryOptions = <TData = Awaited<ReturnType<typeof listBookings>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBookings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBookingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBookings>>> = ({ signal }) => listBookings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBookings>>, TError, TData> & { queryKey: QueryKey }
}

export type ListBookingsQueryResult = NonNullable<Awaited<ReturnType<typeof listBookings>>>
export type ListBookingsQueryError = ErrorType<unknown>


/**
 * @summary List all bookings
 */

export function useListBookings<TData = Awaited<ReturnType<typeof listBookings>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBookings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListBookingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateBookingUrl = () => {




  return `/api/bookings`
}

/**
 * @summary Create a new booking
 */
export const createBooking = async (bookingInput: BookingInput, options?: RequestInit): Promise<Booking> => {

  return customFetch<Booking>(getCreateBookingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookingInput,)
  }
);}




export const getCreateBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingInput>}, TContext> => {

const mutationKey = ['createBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBooking>>, {data: BodyType<BookingInput>}> = (props) => {
          const {data} = props ?? {};

          return  createBooking(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof createBooking>>>
    export type CreateBookingMutationBody = BodyType<BookingInput>
    export type CreateBookingMutationError = ErrorType<unknown>

    /**
 * @summary Create a new booking
 */
export const useCreateBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBooking>>, TError,{data: BodyType<BookingInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createBooking>>,
        TError,
        {data: BodyType<BookingInput>},
        TContext
      > => {
      return useMutation(getCreateBookingMutationOptions(options));
    }

export const getGetBookingsSummaryUrl = () => {




  return `/api/bookings/summary`
}

/**
 * @summary Get bookings summary statistics
 */
export const getBookingsSummary = async ( options?: RequestInit): Promise<BookingsSummary> => {

  return customFetch<BookingsSummary>(getGetBookingsSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBookingsSummaryQueryKey = () => {
    return [
    `/api/bookings/summary`
    ] as const;
    }


export const getGetBookingsSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getBookingsSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBookingsSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookingsSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingsSummary>>> = ({ signal }) => getBookingsSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookingsSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBookingsSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingsSummary>>>
export type GetBookingsSummaryQueryError = ErrorType<unknown>


/**
 * @summary Get bookings summary statistics
 */

export function useGetBookingsSummary<TData = Awaited<ReturnType<typeof getBookingsSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBookingsSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBookingsSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListUpcomingBookingsUrl = () => {




  return `/api/bookings/upcoming`
}

/**
 * @summary List upcoming confirmed bookings
 */
export const listUpcomingBookings = async ( options?: RequestInit): Promise<Booking[]> => {

  return customFetch<Booking[]>(getListUpcomingBookingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUpcomingBookingsQueryKey = () => {
    return [
    `/api/bookings/upcoming`
    ] as const;
    }


export const getListUpcomingBookingsQueryOptions = <TData = Awaited<ReturnType<typeof listUpcomingBookings>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUpcomingBookings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUpcomingBookingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUpcomingBookings>>> = ({ signal }) => listUpcomingBookings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUpcomingBookings>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUpcomingBookingsQueryResult = NonNullable<Awaited<ReturnType<typeof listUpcomingBookings>>>
export type ListUpcomingBookingsQueryError = ErrorType<unknown>


/**
 * @summary List upcoming confirmed bookings
 */

export function useListUpcomingBookings<TData = Awaited<ReturnType<typeof listUpcomingBookings>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUpcomingBookings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUpcomingBookingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetBookingUrl = (id: number,) => {




  return `/api/bookings/${id}`
}

/**
 * @summary Get booking by ID
 */
export const getBooking = async (id: number, options?: RequestInit): Promise<Booking> => {

  return customFetch<Booking>(getGetBookingUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBookingQueryKey = (id: number,) => {
    return [
    `/api/bookings/${id}`
    ] as const;
    }


export const getGetBookingQueryOptions = <TData = Awaited<ReturnType<typeof getBooking>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBooking>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookingQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBooking>>> = ({ signal }) => getBooking(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBooking>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBookingQueryResult = NonNullable<Awaited<ReturnType<typeof getBooking>>>
export type GetBookingQueryError = ErrorType<void>


/**
 * @summary Get booking by ID
 */

export function useGetBooking<TData = Awaited<ReturnType<typeof getBooking>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBooking>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBookingQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateBookingUrl = (id: number,) => {




  return `/api/bookings/${id}`
}

/**
 * @summary Update booking status or details
 */
export const updateBooking = async (id: number,
    bookingUpdate: BookingUpdate, options?: RequestInit): Promise<Booking> => {

  return customFetch<Booking>(getUpdateBookingUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookingUpdate,)
  }
);}




export const getUpdateBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingUpdate>}, TContext> => {

const mutationKey = ['updateBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBooking>>, {id: number;data: BodyType<BookingUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBooking(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBookingMutationResult = NonNullable<Awaited<ReturnType<typeof updateBooking>>>
    export type UpdateBookingMutationBody = BodyType<BookingUpdate>
    export type UpdateBookingMutationError = ErrorType<unknown>

    /**
 * @summary Update booking status or details
 */
export const useUpdateBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBooking>>, TError,{id: number;data: BodyType<BookingUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateBooking>>,
        TError,
        {id: number;data: BodyType<BookingUpdate>},
        TContext
      > => {
      return useMutation(getUpdateBookingMutationOptions(options));
    }

export const getDeleteBookingUrl = (id: number,) => {




  return `/api/bookings/${id}`
}

/**
 * @summary Delete a booking
 */
export const deleteBooking = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteBookingUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteBookingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBooking>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBooking>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteBooking'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBooking>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteBooking(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBookingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBooking>>>

    export type DeleteBookingMutationError = ErrorType<unknown>

    /**
 * @summary Delete a booking
 */
export const useDeleteBooking = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBooking>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteBooking>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteBookingMutationOptions(options));
    }

export const getListGalleryUrl = () => {




  return `/api/gallery`
}

/**
 * @summary List gallery photos
 */
export const listGallery = async ( options?: RequestInit): Promise<GalleryPhoto[]> => {

  return customFetch<GalleryPhoto[]>(getListGalleryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGalleryQueryKey = () => {
    return [
    `/api/gallery`
    ] as const;
    }


export const getListGalleryQueryOptions = <TData = Awaited<ReturnType<typeof listGallery>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGallery>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGalleryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGallery>>> = ({ signal }) => listGallery({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGallery>>, TError, TData> & { queryKey: QueryKey }
}

export type ListGalleryQueryResult = NonNullable<Awaited<ReturnType<typeof listGallery>>>
export type ListGalleryQueryError = ErrorType<unknown>


/**
 * @summary List gallery photos
 */

export function useListGallery<TData = Awaited<ReturnType<typeof listGallery>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listGallery>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListGalleryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getAddGalleryPhotoUrl = () => {




  return `/api/gallery`
}

/**
 * @summary Add a gallery photo
 */
export const addGalleryPhoto = async (galleryPhotoInput: GalleryPhotoInput, options?: RequestInit): Promise<GalleryPhoto> => {

  return customFetch<GalleryPhoto>(getAddGalleryPhotoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      galleryPhotoInput,)
  }
);}




export const getAddGalleryPhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addGalleryPhoto>>, TError,{data: BodyType<GalleryPhotoInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addGalleryPhoto>>, TError,{data: BodyType<GalleryPhotoInput>}, TContext> => {

const mutationKey = ['addGalleryPhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addGalleryPhoto>>, {data: BodyType<GalleryPhotoInput>}> = (props) => {
          const {data} = props ?? {};

          return  addGalleryPhoto(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddGalleryPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof addGalleryPhoto>>>
    export type AddGalleryPhotoMutationBody = BodyType<GalleryPhotoInput>
    export type AddGalleryPhotoMutationError = ErrorType<unknown>

    /**
 * @summary Add a gallery photo
 */
export const useAddGalleryPhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addGalleryPhoto>>, TError,{data: BodyType<GalleryPhotoInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addGalleryPhoto>>,
        TError,
        {data: BodyType<GalleryPhotoInput>},
        TContext
      > => {
      return useMutation(getAddGalleryPhotoMutationOptions(options));
    }

