/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all wedding services
 */
export declare const ListServicesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>;
export declare const ListServicesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>, "many">;
/**
 * @summary Create a new service
 */
export declare const CreateServiceBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodString;
    featured: zod.ZodOptional<zod.ZodBoolean>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    description: string;
    price: number;
    category: string;
    priceNote?: string | undefined;
    featured?: boolean | undefined;
    imageUrl?: string | undefined;
}, {
    name: string;
    description: string;
    price: number;
    category: string;
    priceNote?: string | undefined;
    featured?: boolean | undefined;
    imageUrl?: string | undefined;
}>;
/**
 * @summary List featured services for homepage
 */
export declare const ListFeaturedServicesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>;
export declare const ListFeaturedServicesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>, "many">;
/**
 * @summary Get service by ID
 */
export declare const GetServiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetServiceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>;
/**
 * @summary Update a service
 */
export declare const UpdateServiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateServiceBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodOptional<zod.ZodNumber>;
    priceNote: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodOptional<zod.ZodString>;
    featured: zod.ZodOptional<zod.ZodBoolean>;
    imageUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    priceNote?: string | undefined;
    category?: string | undefined;
    featured?: boolean | undefined;
    imageUrl?: string | undefined;
}, {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    priceNote?: string | undefined;
    category?: string | undefined;
    featured?: boolean | undefined;
    imageUrl?: string | undefined;
}>;
export declare const UpdateServiceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodString;
    price: zod.ZodNumber;
    priceNote: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    featured: zod.ZodBoolean;
    imageUrl: zod.ZodNullable<zod.ZodString>;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}, {
    id: number;
    name: string;
    description: string;
    price: number;
    category: string;
    featured: boolean;
    imageUrl: string | null;
    priceNote?: string | null | undefined;
    createdAt?: string | undefined;
}>;
/**
 * @summary Delete a service
 */
export declare const DeleteServiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all bookings
 */
export declare const ListBookingsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>;
export declare const ListBookingsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>, "many">;
/**
 * @summary Create a new booking
 */
export declare const CreateBookingBody: zod.ZodObject<{
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNumber>;
    serviceId: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    guestCount?: number | undefined;
    serviceId?: number | undefined;
    notes?: string | undefined;
}, {
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    guestCount?: number | undefined;
    serviceId?: number | undefined;
    notes?: string | undefined;
}>;
/**
 * @summary Get bookings summary statistics
 */
export declare const GetBookingsSummaryResponse: zod.ZodObject<{
    total: zod.ZodNumber;
    pending: zod.ZodNumber;
    confirmed: zod.ZodNumber;
    cancelled: zod.ZodNumber;
    upcomingThisMonth: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    pending: number;
    confirmed: number;
    cancelled: number;
    total: number;
    upcomingThisMonth: number;
}, {
    pending: number;
    confirmed: number;
    cancelled: number;
    total: number;
    upcomingThisMonth: number;
}>;
/**
 * @summary List upcoming confirmed bookings
 */
export declare const ListUpcomingBookingsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>;
export declare const ListUpcomingBookingsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>, "many">;
/**
 * @summary Get booking by ID
 */
export declare const GetBookingParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetBookingResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>;
/**
 * @summary Update booking status or details
 */
export declare const UpdateBookingParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateBookingBody: zod.ZodObject<{
    clientName: zod.ZodOptional<zod.ZodString>;
    clientPhone: zod.ZodOptional<zod.ZodString>;
    clientEmail: zod.ZodOptional<zod.ZodString>;
    weddingDate: zod.ZodOptional<zod.ZodString>;
    venue: zod.ZodOptional<zod.ZodString>;
    guestCount: zod.ZodOptional<zod.ZodNumber>;
    status: zod.ZodOptional<zod.ZodEnum<["pending", "confirmed", "cancelled"]>>;
    serviceId: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: "pending" | "confirmed" | "cancelled" | undefined;
    clientName?: string | undefined;
    clientPhone?: string | undefined;
    clientEmail?: string | undefined;
    weddingDate?: string | undefined;
    venue?: string | undefined;
    guestCount?: number | undefined;
    serviceId?: number | undefined;
    notes?: string | undefined;
    totalPrice?: number | undefined;
}, {
    status?: "pending" | "confirmed" | "cancelled" | undefined;
    clientName?: string | undefined;
    clientPhone?: string | undefined;
    clientEmail?: string | undefined;
    weddingDate?: string | undefined;
    venue?: string | undefined;
    guestCount?: number | undefined;
    serviceId?: number | undefined;
    notes?: string | undefined;
    totalPrice?: number | undefined;
}>;
export declare const UpdateBookingResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientName: zod.ZodString;
    clientPhone: zod.ZodString;
    clientEmail: zod.ZodString;
    weddingDate: zod.ZodString;
    venue: zod.ZodString;
    guestCount: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    status: zod.ZodEnum<["pending", "confirmed", "cancelled"]>;
    serviceId: zod.ZodNullable<zod.ZodNumber>;
    serviceName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    notes: zod.ZodNullable<zod.ZodString>;
    totalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}, {
    status: "pending" | "confirmed" | "cancelled";
    id: number;
    createdAt: string;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    serviceId: number | null;
    notes: string | null;
    guestCount?: number | null | undefined;
    serviceName?: string | null | undefined;
    totalPrice?: number | null | undefined;
}>;
/**
 * @summary Delete a booking
 */
export declare const DeleteBookingParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List gallery photos
 */
export declare const ListGalleryResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    imageUrl: zod.ZodString;
    title: zod.ZodString;
    category: zod.ZodString;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: string;
    imageUrl: string;
    title: string;
    createdAt?: string | undefined;
}, {
    id: number;
    category: string;
    imageUrl: string;
    title: string;
    createdAt?: string | undefined;
}>;
export declare const ListGalleryResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    imageUrl: zod.ZodString;
    title: zod.ZodString;
    category: zod.ZodString;
    createdAt: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    id: number;
    category: string;
    imageUrl: string;
    title: string;
    createdAt?: string | undefined;
}, {
    id: number;
    category: string;
    imageUrl: string;
    title: string;
    createdAt?: string | undefined;
}>, "many">;
/**
 * @summary Add a gallery photo
 */
export declare const AddGalleryPhotoBody: zod.ZodObject<{
    imageUrl: zod.ZodString;
    title: zod.ZodString;
    category: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    category: string;
    imageUrl: string;
    title: string;
}, {
    category: string;
    imageUrl: string;
    title: string;
}>;
//# sourceMappingURL=api.d.ts.map