/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Service {
  id: number;
  name: string;
  description: string;
  price: number;
  /** @nullable */
  priceNote?: string | null;
  category: string;
  featured: boolean;
  /** @nullable */
  imageUrl: string | null;
  createdAt?: string;
}

export interface ServiceInput {
  /** @minLength 1 */
  name: string;
  description: string;
  price: number;
  priceNote?: string;
  category: string;
  featured?: boolean;
  imageUrl?: string;
}

export interface ServiceUpdate {
  name?: string;
  description?: string;
  price?: number;
  priceNote?: string;
  category?: string;
  featured?: boolean;
  imageUrl?: string;
}

export type BookingStatus = typeof BookingStatus[keyof typeof BookingStatus];


export const BookingStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
} as const;

export interface Booking {
  id: number;
  clientName: string;
  clientPhone: string;
  clientEmail: string;
  weddingDate: string;
  venue: string;
  /** @nullable */
  guestCount?: number | null;
  status: BookingStatus;
  /** @nullable */
  serviceId: number | null;
  /** @nullable */
  serviceName?: string | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  totalPrice?: number | null;
  createdAt: string;
}

export interface BookingInput {
  /** @minLength 1 */
  clientName: string;
  clientPhone: string;
  clientEmail: string;
  weddingDate: string;
  venue: string;
  guestCount?: number;
  serviceId?: number;
  notes?: string;
}

export type BookingUpdateStatus = typeof BookingUpdateStatus[keyof typeof BookingUpdateStatus];


export const BookingUpdateStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
} as const;

export interface BookingUpdate {
  clientName?: string;
  clientPhone?: string;
  clientEmail?: string;
  weddingDate?: string;
  venue?: string;
  guestCount?: number;
  status?: BookingUpdateStatus;
  serviceId?: number;
  notes?: string;
  totalPrice?: number;
}

export interface BookingsSummary {
  total: number;
  pending: number;
  confirmed: number;
  cancelled: number;
  upcomingThisMonth: number;
}

export interface GalleryPhoto {
  id: number;
  imageUrl: string;
  title: string;
  category: string;
  createdAt?: string;
}

export interface GalleryPhotoInput {
  imageUrl: string;
  title: string;
  category: string;
}

