/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
import type { BookingUpdateStatus } from './bookingUpdateStatus';
export interface BookingUpdate {
    clientName?: string;
    clientPhone?: string;
    clientEmail?: string;
    weddingDate?: string;
    venue?: string;
    guestCount?: number;
    status?: BookingUpdateStatus;
    serviceId?: number;
    notes?: string;
    totalPrice?: number;
}
//# sourceMappingURL=bookingUpdate.d.ts.map