/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export type BookingStatus = typeof BookingStatus[keyof typeof BookingStatus];
export declare const BookingStatus: {
    readonly pending: "pending";
    readonly confirmed: "confirmed";
    readonly cancelled: "cancelled";
};
//# sourceMappingURL=bookingStatus.d.ts.map