/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface BookingsSummary {
    total: number;
    pending: number;
    confirmed: number;
    cancelled: number;
    upcomingThisMonth: number;
}
//# sourceMappingURL=bookingsSummary.d.ts.map