/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface BookingInput {
    /** @minLength 1 */
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    guestCount?: number;
    serviceId?: number;
    notes?: string;
}
//# sourceMappingURL=bookingInput.d.ts.map