/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
import type { BookingStatus } from './bookingStatus';
export interface Booking {
    id: number;
    clientName: string;
    clientPhone: string;
    clientEmail: string;
    weddingDate: string;
    venue: string;
    /** @nullable */
    guestCount?: number | null;
    status: BookingStatus;
    /** @nullable */
    serviceId: number | null;
    /** @nullable */
    serviceName?: string | null;
    /** @nullable */
    notes: string | null;
    /** @nullable */
    totalPrice?: number | null;
    createdAt: string;
}
//# sourceMappingURL=booking.d.ts.map