/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface GalleryPhoto {
    id: number;
    imageUrl: string;
    title: string;
    category: string;
    createdAt?: string;
}
//# sourceMappingURL=galleryPhoto.d.ts.map