/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface GalleryPhotoInput {
    imageUrl: string;
    title: string;
    category: string;
}
//# sourceMappingURL=galleryPhotoInput.d.ts.map