/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface Service {
    id: number;
    name: string;
    description: string;
    price: number;
    /** @nullable */
    priceNote?: string | null;
    category: string;
    featured: boolean;
    /** @nullable */
    imageUrl: string | null;
    createdAt?: string;
}
//# sourceMappingURL=service.d.ts.map