/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Wedding booking API
 * OpenAPI spec version: 0.1.0
 */
export interface ServiceUpdate {
    name?: string;
    description?: string;
    price?: number;
    priceNote?: string;
    category?: string;
    featured?: boolean;
    imageUrl?: string;
}
//# sourceMappingURL=serviceUpdate.d.ts.map